spring:
  thymeleaf:
    cache: false
    cache-period: 0
    prefix: file:src/main/resources/templates/
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2.console.enabled: true
